version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
    volumes:
      - sonarqubedata:/opt/sonarqube
  elk:
    image: sebp/elk
    container_name: elk
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
volumes:
  sonarqubedata: